# Generated by Django 4.0 on 2023-11-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0016_user_dept_user_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClubInfo',
        ),
        migrations.DeleteModel(
            name='EmailVerify',
        ),
    ]
