# Generated by Django 4.0 on 2023-11-19 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_search'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file5',
        ),
        migrations.AddField(
            model_name='post',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.CharField(max_length=100),
        ),
    ]
