# Generated by Django 4.0 on 2023-11-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_remove_post_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recommend',
            field=models.IntegerField(default=0),
        ),
    ]
