# Generated by Django 4.2.7 on 2023-11-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_post_keyword1_post_keyword2'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
