# Generated by Django 4.2.7 on 2023-11-21 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_search_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
