# Generated by Django 4.2.7 on 2023-11-21 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_delete_board'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
